# Generated by Django 5.2.7 on 2026-04-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_academy_user_delete_academyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='address_text',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
