# Generated by Django 5.2.7 on 2026-04-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_academy_address_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='address_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
