# Generated by Django 5.2.5 on 2025-08-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
