# Generated by Django 5.2.7 on 2026-04-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_remove_trainer_availability_remove_trainer_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
