# Generated by Django 5.2.5 on 2025-08-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='area',
        ),
    ]
