# Generated by Django 5.2.5 on 2025-08-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_rename_name_location_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
