# Generated by Django 5.2.5 on 2025-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_remove_course_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
