# Generated by Django 5.2.5 on 2025-09-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
