# Generated by Django 5.2.7 on 2026-02-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_academy_course_academy_trainer_academy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
    ]
