# Generated by Django 5.2.7 on 2026-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_remove_location_address_remove_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='location',
        ),
        migrations.AddField(
            model_name='academy',
            name='location',
            field=models.ManyToManyField(blank=True, to='academy.location'),
        ),
    ]
