# Generated by Django 5.2.7 on 2026-02-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_remove_academy_location_academy_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='phone',
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('academy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='academy.academy')),
            ],
        ),
    ]
