# Generated by Django 5.2.7 on 2026-02-10 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_remove_academy_email_remove_academy_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='academy',
        ),
        migrations.AddField(
            model_name='academy',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy_contact_info', to='academy.contactinfo'),
        ),
    ]
