# Generated by Django 5.2.7 on 2026-02-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_remove_contactinfo_academy_academy_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='website',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='academy.academy'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='type',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('website', 'Website')], default='phone', max_length=10),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.location'),
        ),
    ]
