# Generated by Django 5.2.7 on 2026-02-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_remove_trainer_phone_contactinfo_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='address',
            field=models.URLField(max_length=255),
        ),
    ]
