# Generated by Django 5.2.7 on 2026-02-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_alter_academy_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='address',
        ),
        migrations.AddField(
            model_name='academy',
            name='address_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
