# Generated by Django 5.2.7 on 2026-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_remove_academy_address_academy_address_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
