# Generated by Django 5.2.7 on 2026-02-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_alter_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
