# Generated by Django 5.2.7 on 2026-02-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0023_academy_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Automatic')], max_length=10, null=True),
        ),
    ]
