# Generated by Django 5.2.7 on 2026-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0024_course_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
